# Generated by Django 3.1.2 on 2020-10-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lamp",
            fields=[
                (
                    "appliance_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.appliance",
                    ),
                ),
                ("state", models.BooleanField(default=False, verbose_name="state")),
            ],
            options={"verbose_name": "Lamp", "verbose_name_plural": "Lamps",},
            bases=("home.appliance",),
        ),
    ]
