# Generated by Django 3.1.4 on 2020-12-09 20:11

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socket",
            name="state",
            field=django_fsm.FSMField(default="off", max_length=50, protected=True),
        ),
    ]
