# Generated by Django 3.1.2 on 2020-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates if this user should be treated as active.",
                verbose_name="active",
            ),
        ),
    ]
