# Generated by Django 3.1.3 on 2020-11-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temp_sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempsensor",
            name="last_read",
            field=models.FloatField(null=True, verbose_name="last read"),
        ),
        migrations.CreateModel(
            name="TempHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.FloatField(verbose_name="temperature value")),
                ("read_time", models.DateTimeField(auto_now_add=True, verbose_name="read time")),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="temp_sensor.tempsensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Reading",
                "verbose_name_plural": "Temperature Readings",
            },
        ),
    ]
