# Generated by Django 3.1.3 on 2020-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temp_sensor", "0002_auto_20201118_2151"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempsensor",
            name="last_read_time",
            field=models.DateTimeField(null=True, verbose_name="last read time"),
        ),
        migrations.AddField(
            model_name="tempsensor",
            name="temp_tolerance",
            field=models.FloatField(default=0.25, verbose_name="change tolerance"),
        ),
    ]
