# Generated by Django 3.1.2 on 2020-10-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_auto_20201022_2356"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roller",
            fields=[
                (
                    "appliance_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.appliance",
                    ),
                ),
                ("open", models.BooleanField(default=False, verbose_name="open")),
            ],
            options={
                "verbose_name": "Roller",
                "verbose_name_plural": "Rollers",
            },
            bases=("home.appliance",),
        ),
    ]
